# Generated by Django 3.0.7 on 2020-07-25 23:06

import apps.comunidades.models
import config.extrafields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComunidadEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('photo', config.extrafields.ContentTypeRestrictedFileField(upload_to=apps.comunidades.models.upload_dinamic_dir)),
                ('markdown', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
