# Generated by Django 3.0.7 on 2020-08-31 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidadentry',
            name='tipo',
            field=models.CharField(choices=[('AFROS', 'AFROS'), ('INDIGENAS', 'INDIGENAS')], default='INDIGENAS', max_length=100),
            preserve_default=False,
        ),
    ]
