# Generated by Django 3.0.7 on 2020-11-24 20:10

import apps.comunidades.models
import config.extrafields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades', '0003_auto_20200922_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', config.extrafields.ContentTypeRestrictedFileField(upload_to=apps.comunidades.models.upload_dinamic_imagenes)),
            ],
        ),
    ]
