# Generated by Django 3.0.7 on 2020-11-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades', '0005_auto_20201124_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunidadentry',
            name='tipo',
            field=models.CharField(choices=[('MAIN_AFROS', 'AFROS'), ('MAIN_INDIGENAS', 'INDIGENAS'), ('AFROS', 'COMUNIDADES AFROS'), ('INDIGENAS', 'COMUNIDADES INDIGENAS'), ('COSTUMBRES', 'COSTUMBRES'), ('COCINA', 'COCINA'), ('FOTOS', 'FOTOS'), ('BIENES', 'BIENES'), ('MEDICINA', 'MEDICINA'), ('MERCADO_CAMPESINO', 'MERCADO CAMPESINO')], max_length=100),
        ),
    ]
