version: '3'

services:

  db:
    image: postgres
    container_name: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.production/.db
    ports:
      - 5432:5432

  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: cinda
    container_name: django_app
    restart: always
    volumes:
      - static_volume:/app/staticfiles
      - ./media:/app/media
    env_file:
      - ./.envs/.production/.django
    command: /start

  nginx:
    restart: always
    container_name: nginx_server
    depends_on:
      - django
    volumes:
      - static_volume:/app/staticfiles
      - ./media:/app/media
    build:
      context: ./compose/production/nginx
    ports:
      - "80:80"

  daphne:
    image: cinda
    restart: always
    env_file:
      - ./.envs/.production/.django
    command: /start-daphne


  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  static_volume: