# Generated by Django 3.0.7 on 2020-07-13 16:48

import apps.users.models
import config.extrafields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=config.extrafields.ContentTypeRestrictedFileField(blank=True, upload_to=apps.users.models.upload_dinamic_dir),
        ),
    ]
